import { DEFAULT_PARAMETERS } from './profile'
import type { ChallengeScenario } from './types'

export const CHALLENGES: ChallengeScenario[] = [
  {
    id: 'baseline',
    title: 'CASE 01 · Quiet bench',
    cue: '기준 조건에서 margin이 가장 좁은 위치를 찾으세요.',
    parameters: DEFAULT_PARAMETERS,
    expectedDiagnosis: '정상 기준 파형',
    evidence: '모든 sample의 margin이 0 dB 이상',
    explanation: '기준 파형은 교육용 corridor 안에서 ramp, plateau, off-region을 모두 유지합니다.',
    expectedTrace: { pass: true, firstRegion: null, firstBoundary: null, worstRegion: null, worstBoundary: null, minimumViolationGroups: 0 },
  },
  {
    id: 'early-timing',
    title: 'CASE 02 · Too soon',
    cue: 'Leading edge가 mask보다 먼저 나타납니다.',
    parameters: { ...DEFAULT_PARAMETERS, timingOffsetUs: -8 },
    expectedDiagnosis: 'PA enable 또는 trigger가 너무 이름',
    evidence: 'pre-burst/ramp-up 영역의 upper boundary 이탈',
    explanation: '전체 trace가 왼쪽으로 이동해 off-region 제한을 먼저 침범합니다.',
    expectedTrace: { pass: false, firstRegion: 'pre-burst', firstBoundary: 'upper', worstRegion: 'ramp-down', worstBoundary: 'lower', minimumViolationGroups: 3 },
  },
  {
    id: 'late-ramp',
    title: 'CASE 03 · Late arrival',
    cue: 'Burst 시작 시점에 nominal power에 도달하지 못합니다.',
    parameters: { ...DEFAULT_PARAMETERS, timingOffsetUs: 10, rampUpUs: 10 },
    expectedDiagnosis: 'Ramp-up 또는 bias sequence가 늦음',
    evidence: 'ramp-up 영역의 lower boundary 이탈',
    explanation: 'PA turn-on 기준이 늦어져 start corridor가 요구하는 전력보다 아래에 머뭅니다.',
    expectedTrace: { pass: false, firstRegion: 'ramp-up', firstBoundary: 'lower', worstRegion: 'ramp-up', worstBoundary: 'lower', minimumViolationGroups: 3 },
  },
  {
    id: 'overshoot',
    title: 'CASE 04 · Hot start',
    cue: 'Turn-on 직후 한 번 크게 치솟고 서서히 안정됩니다.',
    parameters: { ...DEFAULT_PARAMETERS, overshootDb: 2.8, settlingUs: 18 },
    expectedDiagnosis: 'Turn-on overshoot가 큼',
    evidence: 'early-settling 영역의 upper boundary 이탈',
    explanation: 'Control step에 대한 응답이 너무 커 초기 plateau 상한을 넘습니다.',
    expectedTrace: { pass: false, firstRegion: 'early-settling', firstBoundary: 'upper', worstRegion: 'early-settling', worstBoundary: 'upper', minimumViolationGroups: 1 },
  },
  {
    id: 'ringing',
    title: 'CASE 05 · Unquiet loop',
    cue: '초기 plateau에서 여러 개의 peak가 반복됩니다.',
    parameters: { ...DEFAULT_PARAMETERS, overshootDb: 1, ringingDb: 1.8, settlingUs: 34 },
    expectedDiagnosis: 'Control path가 underdamped 상태',
    evidence: 'early-settling 영역에 반복 upper violation',
    explanation: 'Underdamped response의 반복 peak가 early-settling 상한을 여러 번 침범합니다.',
    expectedTrace: { pass: false, firstRegion: 'early-settling', firstBoundary: 'upper', worstRegion: 'early-settling', worstBoundary: 'upper', minimumViolationGroups: 4 },
  },
  {
    id: 'high-noise',
    title: 'CASE 06 · Door left open',
    cue: 'Useful burst는 깨끗하지만 burst 밖 power가 높습니다.',
    parameters: { ...DEFAULT_PARAMETERS, noiseFloorDbc: -24 },
    expectedDiagnosis: 'Off-region leakage 또는 noise floor가 높음',
    evidence: 'pre/post-burst upper boundary 이탈',
    explanation: 'Plateau만 보면 정상처럼 보이지만 off-region 제한을 만족하지 못합니다.',
    expectedTrace: { pass: false, firstRegion: 'pre-burst', firstBoundary: 'upper', worstRegion: 'pre-burst', worstBoundary: 'upper', minimumViolationGroups: 4 },
  },
]
