import type { ParameterDefinition, PvTParameters, SimulationProfile } from './types'

export const DEFAULT_PARAMETERS: PvTParameters = {
  rampUpUs: 20,
  rampDownUs: 20,
  timingOffsetUs: 0,
  overshootDb: 0.35,
  settlingUs: 12,
  ringingDb: 0.15,
  noiseFloorDbc: -62,
  seed: 23,
}

export const EDUCATIONAL_PROFILE: SimulationProfile = {
  id: 'dcs1800-ms-gmsk-normal-educational-v1',
  name: 'DCS 1800 · MS Uplink · GMSK Normal Burst',
  context: '교육용 상대 전력 모델 · nominal plateau 0 dBc 기준',
  educationalOnly: true,
  source: '3GPP TS 45.002 / 45.004 / 45.005 / 51.010-1 source family',
  specVersion: 'Educational profile v1 · source-family mapping only',
  assumptions: [
    'Useful burst window is normalized to 0…542.8 µs.',
    'Mask corners are an educational corridor, not official conformance limits.',
    'Power is referenced to the nominal plateau amplitude before transient terms.',
  ],
  burstStartUs: 0,
  burstEndUs: 542.8,
  chartStartUs: -32,
  chartEndUs: 574.8,
  mask: [
    { timeUs: -32, upperDbc: -30, lowerDbc: null },
    { timeUs: -20, upperDbc: -30, lowerDbc: null },
    { timeUs: -18, upperDbc: -29, lowerDbc: null },
    { timeUs: -16, upperDbc: -17, lowerDbc: null },
    { timeUs: -14, upperDbc: -11, lowerDbc: -44 },
    { timeUs: -12, upperDbc: -7, lowerDbc: -36 },
    { timeUs: -10, upperDbc: -4, lowerDbc: -30 },
    { timeUs: -8, upperDbc: -2, lowerDbc: -18 },
    { timeUs: -6, upperDbc: 0, lowerDbc: -12 },
    { timeUs: -4, upperDbc: 1, lowerDbc: -8 },
    { timeUs: 0, upperDbc: 1, lowerDbc: -6 },
    { timeUs: 8, upperDbc: 1, lowerDbc: -1 },
    { timeUs: 534.8, upperDbc: 1, lowerDbc: -1 },
    { timeUs: 542.8, upperDbc: 1, lowerDbc: -6 },
    { timeUs: 546.8, upperDbc: 1, lowerDbc: -8 },
    { timeUs: 548.8, upperDbc: 0, lowerDbc: -12 },
    { timeUs: 550.8, upperDbc: -2, lowerDbc: -18 },
    { timeUs: 552.8, upperDbc: -4, lowerDbc: -30 },
    { timeUs: 554.8, upperDbc: -7, lowerDbc: -36 },
    { timeUs: 556.8, upperDbc: -11, lowerDbc: -44 },
    { timeUs: 558.8, upperDbc: -17, lowerDbc: null },
    { timeUs: 560.8, upperDbc: -29, lowerDbc: null },
    { timeUs: 562.8, upperDbc: -30, lowerDbc: null },
    { timeUs: 574.8, upperDbc: -30, lowerDbc: null },
  ],
}

export const PARAMETER_DEFINITIONS: ParameterDefinition[] = [
  {
    key: 'rampUpUs',
    label: 'Ramp-up time',
    shortLabel: 'RAMP ↑',
    unit: 'µs',
    min: 10,
    max: 32,
    step: 1,
    explanation: 'PA가 off level에서 nominal power에 도달하는 시간',
  },
  {
    key: 'rampDownUs',
    label: 'Ramp-down time',
    shortLabel: 'RAMP ↓',
    unit: 'µs',
    min: 10,
    max: 32,
    step: 1,
    explanation: 'Nominal power에서 off level로 내려가는 시간',
  },
  {
    key: 'timingOffsetUs',
    label: 'Timing offset',
    shortLabel: 'OFFSET',
    unit: 'µs',
    min: -10,
    max: 10,
    step: 1,
    explanation: '전체 burst가 기준 시간에서 이동한 정도',
  },
  {
    key: 'overshootDb',
    label: 'Turn-on overshoot',
    shortLabel: 'OVER',
    unit: 'dB',
    min: 0,
    max: 4,
    step: 0.1,
    explanation: 'Ramp 직후 nominal power를 초과하는 peak',
  },
  {
    key: 'settlingUs',
    label: 'Settling constant',
    shortLabel: 'SETTLE',
    unit: 'µs',
    min: 4,
    max: 48,
    step: 1,
    explanation: 'Overshoot와 ringing이 감소하는 시간 상수',
  },
  {
    key: 'ringingDb',
    label: 'Ringing amplitude',
    shortLabel: 'RING',
    unit: 'dB',
    min: 0,
    max: 3,
    step: 0.1,
    explanation: 'Turn-on 이후 반복되는 감쇠 진동의 크기',
  },
  {
    key: 'noiseFloorDbc',
    label: 'Off-region floor',
    shortLabel: 'FLOOR',
    unit: 'dBc',
    min: -72,
    max: -22,
    step: 1,
    explanation: 'Burst 바깥에서 보이는 leakage와 noise floor',
  },
]
